/* ══════════════════════════════════════════
   PHONETIC SOUNDS DICTIONARY
══════════════════════════════════════════ */
const vowels = {
  pure: [
    { ipa:"/iː/", mw:"[ee]", name:"Long E", keyword:"he", type:"vowel",
      words:["he","see","feel","team","people","key","ski","machine","belief"],
      spellings:["e — he, me","ee — see, feel","ea — team, read","ie — belief","ey — key","i — ski, machine"],
      tip:"Similar to Spanish /i/ but held slightly longer. Tense the tongue high and spread the lips slightly." },
    { ipa:"/ɪ/", mw:"[ih]", name:"Short I", keyword:"hit", type:"vowel",
      words:["hit","sit","win","big","quick","busy","women","build","gym"],
      spellings:["i — hit, sit","y — gym, symbol","ui — build","u — busy","o — women"],
      tip:"Not the Spanish /i/. The lips are relaxed — not spread. The tongue is high but not fully tense. Much shorter and laxer." },
    { ipa:"/ɛ/", mw:"[eh]", name:"Short E", keyword:"head", type:"vowel",
      words:["head","bed","said","friend","many","any","weather","says","bury"],
      spellings:["e — bed","ea — head, weather","ai — said","ie — friend","a — many, any","u — bury"],
      tip:"Close to Spanish /e/ but a little lower and more open. Don't let it drift up toward /i/." },
    { ipa:"/æ/", mw:"[a]", name:"Short A", keyword:"cap", type:"vowel",
      words:["cap","cat","man","bad","apple","laugh","plaid","half"],
      spellings:["a — cap, cat","au — laugh","ai — plaid"],
      tip:"Doesn't exist in Spanish. Open the mouth wide, push the tongue forward and low. It's the 'trapped' vowel — tense and bright." },
    { ipa:"/ɑ/", mw:"[ah]", name:"Open A", keyword:"cop", type:"vowel",
      words:["cop","hot","father","calm","palm","spa","watch","want"],
      spellings:["o — cop, hot","a — father, calm","al — palm","wa — watch, want"],
      tip:"Like a wide-open, relaxed /a/ pushed back in the throat. The mouth is fully open and the jaw drops." },
    { ipa:"/ə/ or /ʌ/", mw:"[uh]", name:"Schwa / stressed uh", keyword:"cup", type:"vowel",
      words:["cup","fun","done","love","blood","about","sofa","button","pencil"],
      spellings:["u — cup, fun","o — love, done","ou — blood","a — about (unstressed)","o — sofa (unstressed)"],
      tip:"The most common sound in English! Every unstressed syllable tends to become /ə/. Spanish speakers often over-pronounce unstressed vowels — relax them into this neutral 'uh'." },
    { ipa:"/uː/", mw:"[u]", name:"Long OO", keyword:"who", type:"vowel",
      words:["who","food","moon","true","blue","school","through","suit","chew"],
      spellings:["oo — food, moon","u — truth","ue — true, blue","ew — chew, brew","ou — through","ui — suit"],
      tip:"Similar to Spanish /u/ but sometimes starts with a /j/ glide ('you', 'cube'). The lips are tightly rounded." },
    { ipa:"/ʊ/", mw:"[uu]", name:"Short OO", keyword:"took", type:"vowel",
      words:["took","book","foot","good","could","would","should","pull","put"],
      spellings:["oo — book, foot","ou — could, would","u — pull, put","o — wolf"],
      tip:"A short, relaxed version of /uː/. The lips are only loosely rounded. Practice the difference: 'food' vs 'foot'." },
    { ipa:"/ɔː/", mw:"[aw]", name:"AW sound", keyword:"law", type:"vowel",
      words:["law","call","also","thought","caught","ball","walk","water"],
      spellings:["aw — law, saw","al — call, ball, walk","au — caught, water","ou — thought","o — also"],
      tip:"A mid-back rounded vowel. Lips are loosely rounded." }
  ],
  diphthongs: [
    { ipa:"/eɪ/", mw:"[ei]", name:"Long A", keyword:"hey", type:"diphthong",
      words:["hey","day","made","great","they","vein","weigh","break","eight"],
      spellings:["ay — day, say","a_e — made, late","ey — they, hey","ei — vein, eight","ea — break, steak","ai — rain"],
      tip:"Spanish speakers often say a flat /e/. In English, the sound must glide upward — the mouth closes as you say it." },
    { ipa:"/oʊ/", mw:"[ou]", name:"Long O", keyword:"home", type:"diphthong",
      words:["home","go","know","phone","road","though","toe","soul","boat"],
      spellings:["o — go, so","o_e — home, phone","ow — know, show","oa — road, boat","ou — though","oe — toe"],
      tip:"Not the Spanish /o/. It starts in the center and glides toward a rounded /ʊ/ at the end." },
    { ipa:"/aɪ/", mw:"[ai]", name:"Long I", keyword:"hi", type:"diphthong",
      words:["hi","my","time","high","fly","night","buy","pie","eye","guide"],
      spellings:["i_e — time, bike","y — my, fly","igh — night, high","uy — buy","ie — pie","eye — eye","ui — guide"],
      tip:"Starts with a wide open /ɑ/ and glides up toward /ɪ/. The jaw closes as the sound progresses." },
    { ipa:"/aʊ/", mw:"[au]", name:"OW sound", keyword:"how", type:"diphthong",
      words:["how","now","loud","down","about","crowd","out","mouth","couch"],
      spellings:["ow — how, now, crowd","ou — loud, out, about, mouth"],
      tip:"Starts open and the lips round at the end toward /ʊ/. Keep both movements clear." },
    { ipa:"/ɔɪ/", mw:"[oi]", name:"OY sound", keyword:"boy", type:"diphthong",
      words:["boy","voice","coin","toy","oil","noise","royal","foil","joint"],
      spellings:["oy — boy, toy, royal","oi — coin, oil, voice, noise"],
      tip:"Starts with rounded lips /ɔ/ and glides up toward /ɪ/. Make sure the glide is clear." }
  ],
  rcolored: [
    { ipa:"/ɝ/", mw:"[er]", name:"Stressed ER", keyword:"her", type:"rcolored",
      words:["her","bird","word","nurse","earth","first","hurt","work","turn"],
      spellings:["er — her, fern","ir — bird, first","ur — nurse, hurt","or — word, work","ear — earth, learn"],
      tip:"The tongue curls back while the vowel is produced. No equivalent in Spanish. The American R is present even inside the vowel." },
    { ipa:"/ɚ/", mw:"[er]", name:"Unstressed ER", keyword:"bigger", type:"rcolored",
      words:["bigger","butter","doctor","teacher","mother","color","dollar","actor","forever"],
      spellings:["er — bigger, butter, mother","or — doctor, color, actor","ar — dollar, popular"],
      tip:"The unstressed version of /ɝ/. Occurs at the end of most '-er', '-or', '-ar' endings. Very common in American English." },
    { ipa:"/ɑr/", mw:"[ar]", name:"AR sound", keyword:"far", type:"rcolored",
      words:["far","car","heart","park","start","guard","calm","father"],
      spellings:["ar — far, car, park","ear — heart","ua — guard"],
      tip:"A wide-open /ɑ/ followed by the American R curl. Keep the mouth open and curl the tongue back at the end." },
    { ipa:"/ɛr/", mw:"[er]", name:"AIR sound", keyword:"fare", type:"rcolored",
      words:["fare","care","air","there","where","wear","bear","their","mayor"],
      spellings:["are — fare, care","air — air, fair","ere — there, where","ear — wear, bear","eir — their","ayor — mayor"],
      tip:"A mid-front /ɛ/ that transitions into the American R. The tongue starts forward and then curls back." },
    { ipa:"/ɪr/", mw:"[eer]", name:"EAR sound", keyword:"here", type:"rcolored",
      words:["here","ear","fear","deer","pier","weird","beer","cheer","year"],
      spellings:["ere — here","ear — ear, fear, year","eer — deer, beer, cheer","ier — pier","eir — weird"],
      tip:"Starts with the high /iː/ position then curls into the R." },
    { ipa:"/ɔr/", mw:"[or]", name:"OR sound", keyword:"or", type:"rcolored",
      words:["or","for","more","door","four","floor","war","board","born","court"],
      spellings:["or — or, for, born","ore — more, store","oor — door, floor","our — four, court","oar — board, hoarse","ar — war, toward"],
      tip:"A rounded /ɔ/ that flows into the American R. Keep the lips slightly rounded as the tongue curls back." }
  ]
};

const consonants = {
  stops: [
    { ipa:"/p/", mw:"[p]", name:"P sound", keyword:"pen", type:"consonant",
      words:["pen","top","happy","apple","camp"],
      spellings:["p — pen, top","pp — happy, apple"],
      tip:"Aspirated at the start of stressed syllables — you feel a puff of air. Hold your hand in front: 'pen' has a puff, 'spin' does not." },
    { ipa:"/b/", mw:"[b]", name:"B sound", keyword:"big", type:"consonant",
      words:["big","cab","able","baby","job","ebb"],
      spellings:["b — big, cab","bb — ebb"],
      tip:"No aspiration. In Spanish, /b/ between vowels becomes a fricative — in American English, always keep it a full stop." },
    { ipa:"/t/", mw:"[t]", name:"T sound", keyword:"top", type:"consonant",
      words:["top","cat","water","butter","action","nature","question","pizza","Thomas"],
      spellings:["t — top, cat","tt — butter","ti — action, question (= /ʃ/ or /tʃ/)","tu — nature (= /tʃ/)","th — Thomas (= /t/)","zz — pizza (= /ts/)"],
      tip:"Between vowels, American /t/ becomes a quick flap — like a fast /d/. 'Water' and 'butter' use this. Also: 'ti' often sounds like SH (nation) or CH (question)." },
    { ipa:"/d/", mw:"[d]", name:"D sound", keyword:"dog", type:"consonant",
      words:["dog","ride","made","middle","add","loved","could"],
      spellings:["d — dog, ride","dd — middle, add","ed — loved (past tense)","ld — could (silent l)"],
      tip:"At the start of a word, similar to Spanish /d/. Between vowels it can sound like a flap. Focus on voicing." },
    { ipa:"/k/", mw:"[k]", name:"K sound", keyword:"cat", type:"consonant",
      words:["cat","kite","queen","school","fix","account","antique","choir","stomach"],
      spellings:["c — cat, car","k — kite, king","ck — back, clock","qu — queen (= /kw/)","x — fix, box (= /ks/)","cc — account","que — antique","ch — choir, stomach","sc — school"],
      tip:"Aspirated at the start of stressed syllables. Spelled many ways: c, k, ck, ch, and x (as /ks/)." },
    { ipa:"/g/", mw:"[g]", name:"G sound", keyword:"go", type:"consonant",
      words:["go","big","egg","ghost","guest","exact","exhaust"],
      spellings:["g — go, big","gg — egg","gh — ghost","gu — guest, guide","x — exact (= /gz/)"],
      tip:"The voiced version of /k/. 'Gh' is silent in many words but sounds like /g/ in 'ghost' and 'ghoul'." }
  ],
  fricatives: [
    { ipa:"/f/", mw:"[f]", name:"F sound", keyword:"fan", type:"consonant",
      words:["fan","off","phone","cough","laugh","rough","staff"],
      spellings:["f — fan, feel","ff — off, staff","ph — phone, photo","gh — cough, laugh, rough"],
      tip:"Top teeth touch the lower lip, air flows through. 'Ph' always makes this sound. 'Gh' at the end of some words also makes /f/." },
    { ipa:"/v/", mw:"[v]", name:"V sound", keyword:"van", type:"consonant",
      words:["van","have","love","of","vivid","river","cave"],
      spellings:["v — van, vivid","f — of (= /v/)"],
      tip:"The voiced /f/. Spanish doesn't have a true /v/. Top teeth must press on the lower lip and vibrate. One of the most important sounds to master!" },
    { ipa:"/θ/", mw:"[th]", name:"TH voiceless", keyword:"think", type:"consonant",
      words:["think","bath","three","tooth","through","author","birthday"],
      spellings:["th — think, bath, three, through, author, birthday"],
      tip:"Tongue tip between or just behind the top teeth, blow air — no voice. Spanish speakers often substitute /t/, /s/, or /f/." },
    { ipa:"/ð/", mw:"[th]", name:"TH voiced", keyword:"the", type:"consonant",
      words:["the","this","mother","breathe","bathe","father","together","smooth"],
      spellings:["th — the, this, mother, breathe, father"],
      tip:"Same tongue position as voiceless TH but with voicing. Spanish speakers often use /d/ — let the tongue come forward." },
    { ipa:"/s/", mw:"[s]", name:"S sound", keyword:"see", type:"consonant",
      words:["see","miss","city","psychology","scene","science"],
      spellings:["s — see, sun","ss — miss, boss","c — city, center (before e/i)","sc — science, scene","ps — psychology"],
      tip:"Common spelling trap: 'c' before e/i/y makes /s/ (city, cent). 'Ps' at the start — the P is silent (psychology)." },
    { ipa:"/z/", mw:"[z]", name:"Z sound", keyword:"zoo", type:"consonant",
      words:["zoo","fizz","rose","dogs","his","scissors","xylophone"],
      spellings:["z — zoo, zone","zz — fizz","s — rose, his, dogs (plural/voiced)","ss — scissors","x — xylophone"],
      tip:"Most English plurals and verb endings spelled '-s' are actually /z/ ('dogs', 'runs', 'plays'). Not /s/!" },
    { ipa:"/ʃ/", mw:"[sh]", name:"SH sound", keyword:"she", type:"consonant",
      words:["she","ship","nation","special","sure","machine","chef","ocean","sugar","tissue"],
      spellings:["sh — she, ship","ti — nation, action","ci — special, ancient","su — sure, sugar","ch — chef, machine","ce — ocean","ss — tissue"],
      tip:"'Sh' is obvious, but this sound hides in 'ti' (nation), 'ci' (special), 'ch' (chef), and more." },
    { ipa:"/ʒ/", mw:"[zh]", name:"ZH sound", keyword:"measure", type:"consonant",
      words:["measure","vision","usual","beige","genre","garage","Asia","treasure"],
      spellings:["si — vision, Asia","su — measure, treasure, usual","ge — beige, garage","g — genre"],
      tip:"The voiced version of /ʃ/. Rare but important. It's the 's' in 'vision', not /s/ or /ʃ/." },
    { ipa:"/h/", mw:"[h]", name:"H sound", keyword:"hat", type:"consonant",
      words:["hat","ahead","who","hello","behind","whole","vehicle"],
      spellings:["h — hat, hello","wh — who, whole (= /h/)","h — vehicle (often silent)"],
      tip:"American /h/ is a gentle breath — much softer than the Spanish /x/ (as in 'Juan'). Just exhale quietly." }
  ],
  affricates: [
    { ipa:"/tʃ/", mw:"[ch]", name:"CH sound", keyword:"chin", type:"consonant",
      words:["chin","watch","teacher","nature","question","Czech","cello","righteous"],
      spellings:["ch — chin, teacher","tch — watch, catch","tu — nature, future","ti — question","cz — Czech","c — cello","teous — righteous"],
      tip:"A single sound: starts like /t/ and releases as /ʃ/. 'Tu' in words like 'nature' often becomes /tʃ/ in casual American English." },
    { ipa:"/dʒ/", mw:"[j]", name:"J sound", keyword:"job", type:"consonant",
      words:["job","judge","gym","age","bridge","soldier","gradual","education","magic"],
      spellings:["j — job, jump","g — gym, age, magic (before e/i/y)","dge — judge, bridge","di — soldier","du — gradual, education"],
      tip:"The voiced /tʃ/. 'G' before e, i, or y often makes /dʒ/ ('gym', 'gentle'). 'Dge' always makes /dʒ/ ('bridge')." }
  ],
  nasals: [
    { ipa:"/m/", mw:"[m]", name:"M sound", keyword:"man", type:"consonant",
      words:["man","him","summer","dumb","climb","solemn","paradigm"],
      spellings:["m — man, him","mm — summer","mb — dumb, climb (silent b)","mn — solemn, autumn (silent n)","gm — paradigm (silent g)"],
      tip:"Lips together, sound comes through the nose. Watch for silent letters: 'climb' (b silent), 'solemn' (n silent)." },
    { ipa:"/n/", mw:"[n]", name:"N sound", keyword:"no", type:"consonant",
      words:["no","sun","know","knife","gnat","pneumonia","inn","sign"],
      spellings:["n — no, sun","kn — know, knife (silent k)","gn — gnat, sign (silent g)","pn — pneumonia (silent p)","nn — inn"],
      tip:"'Kn' at the start — the K is always silent (know, knee, knight). 'Gn' — the G is silent (gnat, sign)." },
    { ipa:"/ŋ/", mw:"[ng]", name:"NG sound", keyword:"sing", type:"consonant",
      words:["sing","thing","think","long","ring","bank","anchor","jungle"],
      spellings:["ng — sing, ring, long","n — think, bank, anchor (before /k/)","n — jungle (before /g/)"],
      tip:"One sound — back of tongue to soft palate. 'Sing' ends with /ŋ/ only, not /ŋg/." }
  ],
  liquids: [
    { ipa:"/r/", mw:"[r]", name:"American R", keyword:"red", type:"consonant",
      words:["red","car","bird","world","river","write","rhyme","wrap"],
      spellings:["r — red, river","rr — sorry, carry","wr — write, wrap (silent w)","rh — rhyme, rhythm (silent h)"],
      tip:"The signature American sound. The tongue curls back without touching anything. Unlike Spanish trilled /r/. Pronounced even after vowels: 'car', 'bird', 'world'." },
    { ipa:"/l/", mw:"[l]", name:"L sound", keyword:"like", type:"consonant",
      words:["like","call","feel","hello","people","walk","half","calm","would","should"],
      spellings:["l — like, feel","ll — call, hello","le — people (= /əl/)","lk — walk, talk (silent l)","lf — half, calf (silent l)","lm — calm, palm (silent l)","ld — would, should (silent l)"],
      tip:"Two versions: light L (start of syllable) and dark L (end of syllable — almost like a vowel). Many silent L words: 'walk', 'half', 'calm'." },
    { ipa:"/j/", mw:"[y]", name:"Y glide", keyword:"yes", type:"consonant",
      words:["yes","you","year","use","cute","few","onion","million","tune"],
      spellings:["y — yes, year","u — use, cute (= /juː/)","ew — few, new (= /juː/)","i — onion, million (= /j/ glide)"],
      tip:"A glide that moves quickly from a high position into the next vowel. 'U' in 'use' and 'cute' starts with this /j/ glide." },
    { ipa:"/w/", mw:"[w]", name:"W sound", keyword:"we", type:"consonant",
      words:["we","world","quick","away","always","one","once","choir"],
      spellings:["w — we, world, away","wh — where, when, what","qu — quick, queen (= /kw/)","o — one, once (= /w/)"],
      tip:"Start with lips tightly rounded like /uː/, then move quickly into the next vowel. 'One' and 'once' start with /w/ despite being spelled with 'o'." }
  ]
};

